// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.example.com/support",
            "email": "support@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/media": {
            "get": {
                "description": "すべてのメディアの一覧を取得します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media"
                ],
                "summary": "メディア一覧を取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.MediaListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/media/upload": {
            "post": {
                "description": "画像ファイルをS3にアップロードし、メディア情報をDBに保存します",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media"
                ],
                "summary": "画像をアップロード",
                "parameters": [
                    {
                        "type": "file",
                        "description": "画像ファイル",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "タイトル",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "説明",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "array",
                        "description": "タグIDの配列",
                        "name": "tag_ids",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.MediaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/media/youtube": {
            "post": {
                "description": "YouTube URLを指定してメディア情報をDBに保存します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media"
                ],
                "summary": "YouTube URLでメディアを作成",
                "parameters": [
                    {
                        "description": "リクエスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.CreateMediaWithYouTubeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.MediaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/media/{id}": {
            "get": {
                "description": "IDを指定してメディア情報を取得します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media"
                ],
                "summary": "メディアを取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "メディアID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.MediaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "IDを指定してメディアを削除します（S3からも削除されます）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media"
                ],
                "summary": "メディアを削除",
                "parameters": [
                    {
                        "type": "string",
                        "description": "メディアID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/media/{id}/tags": {
            "post": {
                "description": "メディアにタグを関連付けます",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media-tags"
                ],
                "summary": "メディアにタグを関連付け",
                "parameters": [
                    {
                        "type": "string",
                        "description": "メディアID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "リクエスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.AssociateTagRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/media/{id}/tags/{tag_id}": {
            "delete": {
                "description": "メディアからタグの関連付けを削除します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media-tags"
                ],
                "summary": "メディアからタグを削除",
                "parameters": [
                    {
                        "type": "string",
                        "description": "メディアID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "タグID",
                        "name": "tag_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tags": {
            "get": {
                "description": "すべてのタグの一覧を取得します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "タグ一覧を取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.TagListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "新しいタグを作成します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "タグを作成",
                "parameters": [
                    {
                        "description": "リクエスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.CreateTagRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.TagResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tags/{id}": {
            "get": {
                "description": "IDを指定してタグ情報を取得します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "タグを取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "タグID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.TagResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "IDを指定してタグ情報を更新します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "タグを更新",
                "parameters": [
                    {
                        "type": "string",
                        "description": "タグID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "リクエスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.UpdateTagRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.TagResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "IDを指定してタグを削除します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "タグを削除",
                "parameters": [
                    {
                        "type": "string",
                        "description": "タグID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tags/{tag_id}/media": {
            "get": {
                "description": "タグIDを指定して関連するメディアの一覧を取得します",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media-tags"
                ],
                "summary": "タグでメディアを取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "タグID",
                        "name": "tag_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.MediaListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_infrastructure_http.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_infrastructure_http.AssociateTagRequest": {
            "description": "メディアにタグを関連付けるリクエスト",
            "type": "object",
            "required": [
                "tag_id"
            ],
            "properties": {
                "tag_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "internal_infrastructure_http.CreateMediaWithYouTubeRequest": {
            "description": "YouTube URLでメディアを作成するリクエスト",
            "type": "object",
            "required": [
                "title",
                "youtube_url"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "これはサンプル動画です"
                },
                "tag_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "550e8400-e29b-41d4-a716-446655440000"
                    ]
                },
                "title": {
                    "type": "string",
                    "example": "サンプル動画"
                },
                "youtube_url": {
                    "type": "string",
                    "example": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
                }
            }
        },
        "internal_infrastructure_http.CreateTagRequest": {
            "description": "タグを作成するリクエスト",
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "新規タグ"
                }
            }
        },
        "internal_infrastructure_http.ErrorResponse": {
            "description": "エラー情報",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error message"
                }
            }
        },
        "internal_infrastructure_http.MediaListResponse": {
            "description": "メディア一覧",
            "type": "object",
            "properties": {
                "media": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_infrastructure_http.MediaResponse"
                    }
                }
            }
        },
        "internal_infrastructure_http.MediaResponse": {
            "description": "メディア情報",
            "type": "object",
            "properties": {
                "cloudfront_url": {
                    "type": "string",
                    "example": "https://cloudfront.net/images/550e8400-e29b-41d4-a716-446655440000.jpg"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "これはサンプル画像です"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "s3_key": {
                    "type": "string",
                    "example": "images/550e8400-e29b-41d4-a716-446655440000.jpg"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_infrastructure_http.TagResponse"
                    }
                },
                "title": {
                    "type": "string",
                    "example": "サンプル画像"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "image",
                        "video"
                    ],
                    "example": "image"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "youtube_url": {
                    "type": "string",
                    "example": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
                }
            }
        },
        "internal_infrastructure_http.MessageResponse": {
            "description": "メッセージ",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "success message"
                }
            }
        },
        "internal_infrastructure_http.TagListResponse": {
            "description": "タグ一覧",
            "type": "object",
            "properties": {
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_infrastructure_http.TagResponse"
                    }
                }
            }
        },
        "internal_infrastructure_http.TagResponse": {
            "description": "タグ情報",
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "name": {
                    "type": "string",
                    "example": "画像"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                }
            }
        },
        "internal_infrastructure_http.UpdateTagRequest": {
            "description": "タグを更新するリクエスト",
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "更新されたタグ名"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Image Server API",
	Description:      "画像・動画保存・表示サービスのAPI",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
